### ISSUE TITLE
Broken STL Files

### ISSUE THREAD

**Issue by m1geo** [LuukEsselbrugge/StepperClock#2]
Hey.

My 3D printer slider (PruserSlic3r) seems to think the STL Files are broken? It complains there are broken edges and faces. Not sure why 😕 I wonder if you are able to reexport them?

Thanks.

**Comment by LuukEsselbrugge** [comment]
Hi I can't find the original file right now. Cura seems to open them fine. Sorry.

**Comment by m1geo** [comment]
No problem. This is what PrusaSlic3r gives. Unfortunately it doesn't ever recover. 
![image](https://user-images.githubusercontent.com/758615/124492824-defa6f80-ddac-11eb-82e8-765e20710138.png)
I'll see what Netfabb makes of it :) Thanks though.
